// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { CreateProjectEndpointData, CreateProjectEndpointResponse, ListProjectsData, ListProjectsResponse, GetProjectData, GetProjectResponse, UpdateProjectEndpointData, UpdateProjectEndpointResponse, DeleteProjectEndpointData, DeleteProjectEndpointResponse, GetStoryboardByProjectIdData, GetStoryboardByProjectIdResponse, CreateStoryboardData, CreateStoryboardResponse, GetStoryboardData, GetStoryboardResponse, UpdateStoryboardData, UpdateStoryboardResponse, GetStoryboardCharactersData, GetStoryboardCharactersResponse, GetStoryboardSettingsData, GetStoryboardSettingsResponse, GetStoryboardScenesData, GetStoryboardScenesResponse, AnalyzeStoryData, AnalyzeStoryResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class DefaultService {
    /**
     * Create Project Endpoint
     * Create a new project for the authenticated user.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * project_in: Project creation data
     *
     * Returns:
     * Created project
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ProjectPublic Successful Response
     * @throws ApiError
     */
    public static createProjectEndpoint(data: CreateProjectEndpointData): CancelablePromise<CreateProjectEndpointResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/projects',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Projects
     * List all projects for the authenticated user.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * offset: Pagination offset
     * limit: Maximum items to return
     *
     * Returns:
     * Dictionary containing projects list and count
     * @param data The data for the request.
     * @param data.offset
     * @param data.limit
     * @returns ProjectsPublic Successful Response
     * @throws ApiError
     */
    public static listProjects(data: ListProjectsData = {}): CancelablePromise<ListProjectsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/projects',
            query: {
                offset: data.offset,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Project
     * Get a specific project by ID.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * project_id: Project UUID
     *
     * Returns:
     * Project if found and owned by user
     *
     * Raises:
     * HTTPException 404: If project not found or not owned by user
     * @param data The data for the request.
     * @param data.projectId
     * @returns ProjectPublic Successful Response
     * @throws ApiError
     */
    public static getProject(data: GetProjectData): CancelablePromise<GetProjectResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/projects/{project_id}',
            path: {
                project_id: data.projectId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Project Endpoint
     * Update a project.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * project_id: Project UUID
     * project_in: Project update data
     *
     * Returns:
     * Updated project
     *
     * Raises:
     * HTTPException 404: If project not found or not owned by user
     * @param data The data for the request.
     * @param data.projectId
     * @param data.requestBody
     * @returns ProjectPublic Successful Response
     * @throws ApiError
     */
    public static updateProjectEndpoint(data: UpdateProjectEndpointData): CancelablePromise<UpdateProjectEndpointResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/projects/{project_id}',
            path: {
                project_id: data.projectId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Project Endpoint
     * Delete a project.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * project_id: Project UUID
     *
     * Returns:
     * Success message
     *
     * Raises:
     * HTTPException 404: If project not found or not owned by user
     * @param data The data for the request.
     * @param data.projectId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteProjectEndpoint(data: DeleteProjectEndpointData): CancelablePromise<DeleteProjectEndpointResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/projects/{project_id}',
            path: {
                project_id: data.projectId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Storyboard By Project Id
     * Get storyboard by project ID.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * project_id: Project UUID
     *
     * Returns:
     * Storyboard if exists, null otherwise
     * @param data The data for the request.
     * @param data.projectId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getStoryboardByProjectId(data: GetStoryboardByProjectIdData): CancelablePromise<GetStoryboardByProjectIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/storyboards/by-project/{project_id}',
            path: {
                project_id: data.projectId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Storyboard
     * Create a new storyboard for a project.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * storyboard_in: Storyboard creation data
     *
     * Returns:
     * Created storyboard
     * @param data The data for the request.
     * @param data.requestBody
     * @returns StoryBoard Successful Response
     * @throws ApiError
     */
    public static createStoryboard(data: CreateStoryboardData): CancelablePromise<CreateStoryboardResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/storyboards',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Storyboard
     * Get a storyboard by ID.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * storyboard_id: Storyboard UUID
     *
     * Returns:
     * Storyboard with related data
     * @param data The data for the request.
     * @param data.storyboardId
     * @returns StoryBoard Successful Response
     * @throws ApiError
     */
    public static getStoryboard(data: GetStoryboardData): CancelablePromise<GetStoryboardResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/storyboards/{storyboard_id}',
            path: {
                storyboard_id: data.storyboardId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Storyboard
     * Update a storyboard.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * storyboard_id: Storyboard UUID
     * storyboard_in: Update data
     *
     * Returns:
     * Updated storyboard
     * @param data The data for the request.
     * @param data.storyboardId
     * @param data.requestBody
     * @returns StoryBoard Successful Response
     * @throws ApiError
     */
    public static updateStoryboard(data: UpdateStoryboardData): CancelablePromise<UpdateStoryboardResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/storyboards/{storyboard_id}',
            path: {
                storyboard_id: data.storyboardId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Storyboard Characters
     * Get all characters for a storyboard.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * storyboard_id: Storyboard UUID
     *
     * Returns:
     * List of characters
     * @param data The data for the request.
     * @param data.storyboardId
     * @returns Character Successful Response
     * @throws ApiError
     */
    public static getStoryboardCharacters(data: GetStoryboardCharactersData): CancelablePromise<GetStoryboardCharactersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/storyboards/{storyboard_id}/characters',
            path: {
                storyboard_id: data.storyboardId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Storyboard Settings
     * Get all settings for a storyboard.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * storyboard_id: Storyboard UUID
     *
     * Returns:
     * List of settings
     * @param data The data for the request.
     * @param data.storyboardId
     * @returns Setting Successful Response
     * @throws ApiError
     */
    public static getStoryboardSettings(data: GetStoryboardSettingsData): CancelablePromise<GetStoryboardSettingsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/storyboards/{storyboard_id}/settings',
            path: {
                storyboard_id: data.storyboardId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Storyboard Scenes
     * Get all scenes for a storyboard.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * storyboard_id: Storyboard UUID
     *
     * Returns:
     * List of scenes ordered by sequence number
     * @param data The data for the request.
     * @param data.storyboardId
     * @returns Scene Successful Response
     * @throws ApiError
     */
    public static getStoryboardScenes(data: GetStoryboardScenesData): CancelablePromise<GetStoryboardScenesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/storyboards/{storyboard_id}/scenes',
            path: {
                storyboard_id: data.storyboardId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Analyze Story
     * Analyze story content and extract characters, settings, and scenes.
     *
     * Args:
     * session: Database session
     * current_user: Authenticated user
     * storyboard_id: Storyboard UUID
     * style: Art style for image generation
     * generate_images: Whether to generate reference images
     *
     * Returns:
     * Analysis results with counts
     * @param data The data for the request.
     * @param data.storyboardId
     * @param data.style
     * @param data.generateImages
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static analyzeStory(data: AnalyzeStoryData): CancelablePromise<AnalyzeStoryResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/storyboards/{storyboard_id}/analyze',
            path: {
                storyboard_id: data.storyboardId
            },
            query: {
                style: data.style,
                generate_images: data.generateImages
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}