// This file is auto-generated by @hey-api/openapi-ts

/**
 * Response model for batch generation operations.
 */
export type BatchGenerationResponse = {
    total: number;
    success_count: number;
    error_count: number;
    errors?: Array<{
        [key: string]: unknown;
    }>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_utils_upload_image = {
    file: (Blob | File);
};

export type Character = {
    id?: string;
    storyboard_id: string;
    name?: (string | null);
    gender?: (string | null);
    age?: (number | null);
    body_build?: (string | null);
    face?: (string | null);
    hair?: (string | null);
    clothes?: (string | null);
    nationality?: (string | null);
    source?: (string | null);
    reference_image_url?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Response model for image generation.
 */
export type ImageGenerationResponse = {
    image_url?: (string | null);
    error?: (string | null);
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProjectCreate = {
    title?: (string | null);
    type?: (string | null);
    status?: (string | null);
    description?: (string | null);
    total_cost?: number;
};

export type ProjectPublic = {
    title?: (string | null);
    type?: (string | null);
    status?: (string | null);
    description?: (string | null);
    total_cost?: number;
    id: string;
    user_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectUpdate = {
    title?: (string | null);
    type?: (string | null);
    status?: (string | null);
    description?: (string | null);
    total_cost?: (number | null);
};

export type Scene = {
    id?: string;
    storyboard_id: string;
    setting_id: (string | null);
    title?: (string | null);
    sequence_number?: number;
    narrative_description?: (string | null);
    visual_description?: (string | null);
    visual_prompt?: (string | null);
    reference_image_url?: (string | null);
    reference_video_url?: (string | null);
};

export type SceneRequest = {
    content: string;
    position?: (number | null);
};

export type Setting = {
    id?: string;
    storyboard_id: string;
    scene_start?: (number | null);
    scene_end?: (number | null);
    name?: (string | null);
    description?: (string | null);
    time_of_day?: (string | null);
    weather?: (string | null);
    art_style?: (string | null);
    reference_image_url?: (string | null);
};

/**
 * Response model for story analysis.
 */
export type StoryAnalysisResponse = {
    characters_count: number;
    settings_count: number;
    scenes_count: number;
    message: string;
};

export type StoryBoard = {
    id?: string;
    project_id: string;
    content?: (string | null);
    scenes_json?: (string | null);
    style?: (string | null);
};

/**
 * Request model for creating a storyboard.
 */
export type StoryBoardCreate = {
    project_id: string;
    content: string;
    style?: (string | null);
};

/**
 * Request model for updating a storyboard.
 */
export type StoryBoardUpdate = {
    content?: (string | null);
    style?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Response model for video generation.
 */
export type VideoGenerationResponse = {
    video_url?: (string | null);
    error?: (string | null);
};

export type CharactersUpdateCharacterEndpointData = {
    characterId: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type CharactersUpdateCharacterEndpointResponse = (Character);

export type CharactersRegenerateCharacterImageData = {
    characterId: string;
    style?: string;
};

export type CharactersRegenerateCharacterImageResponse = (ImageGenerationResponse);

export type CreateProjectEndpointData = {
    requestBody: ProjectCreate;
};

export type CreateProjectEndpointResponse = (ProjectPublic);

export type ListProjectsData = {
    limit?: number;
    offset?: number;
};

export type ListProjectsResponse = (ProjectsPublic);

export type GetProjectData = {
    projectId: string;
};

export type GetProjectResponse = (ProjectPublic);

export type UpdateProjectEndpointData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type UpdateProjectEndpointResponse = (ProjectPublic);

export type DeleteProjectEndpointData = {
    projectId: string;
};

export type DeleteProjectEndpointResponse = (Message);

export type GetStoryboardByProjectIdData = {
    projectId: string;
};

export type GetStoryboardByProjectIdResponse = ((StoryBoard | null));

export type CreateStoryboardData = {
    requestBody: StoryBoardCreate;
};

export type CreateStoryboardResponse = (StoryBoard);

export type GetStoryboardData = {
    storyboardId: string;
};

export type GetStoryboardResponse = (StoryBoard);

export type UpdateStoryboardData = {
    requestBody: StoryBoardUpdate;
    storyboardId: string;
};

export type UpdateStoryboardResponse = (StoryBoard);

export type GetStoryboardCharactersData = {
    storyboardId: string;
};

export type GetStoryboardCharactersResponse = (Array<Character>);

export type GetStoryboardSettingsData = {
    storyboardId: string;
};

export type GetStoryboardSettingsResponse = (Array<Setting>);

export type GetStoryboardScenesData = {
    storyboardId: string;
};

export type GetStoryboardScenesResponse = (Array<Scene>);

export type AnalyzeStoryData = {
    generateImages?: boolean;
    storyboardId: string;
    style?: string;
};

export type AnalyzeStoryResponse = (StoryAnalysisResponse);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ScenesCreateSceneEndpointData = {
    modelOverride?: (string | null);
    provider?: (string | null);
    requestBody: SceneRequest;
    storyboardId: string;
};

export type ScenesCreateSceneEndpointResponse = (Scene);

export type ScenesUpdateSceneEndpointData = {
    requestBody: {
        [key: string]: unknown;
    };
    sceneId: string;
};

export type ScenesUpdateSceneEndpointResponse = (Scene);

export type ScenesRegenerateSceneImageData = {
    sceneId: string;
    style?: string;
};

export type ScenesRegenerateSceneImageResponse = (ImageGenerationResponse);

export type ScenesGenerateSceneImageData = {
    llmProvider?: (string | null);
    sceneId: string;
    style?: (string | null);
};

export type ScenesGenerateSceneImageResponse = (ImageGenerationResponse);

export type ScenesGenerateSceneVideoData = {
    duration?: number;
    sceneId: string;
};

export type ScenesGenerateSceneVideoResponse = (VideoGenerationResponse);

export type ScenesGenerateStoryboardSceneImagesData = {
    endScene?: (number | null);
    llmProvider?: (string | null);
    regenerate?: boolean;
    startScene?: number;
    storyboardId: string;
};

export type ScenesGenerateStoryboardSceneImagesResponse = (BatchGenerationResponse);

export type ScenesGenerateStoryboardSceneVideosData = {
    duration?: number;
    endScene?: (number | null);
    startScene?: number;
    storyboardId: string;
};

export type ScenesGenerateStoryboardSceneVideosResponse = (BatchGenerationResponse);

export type SettingsUpdateSettingEndpointData = {
    requestBody: {
        [key: string]: unknown;
    };
    settingId: string;
};

export type SettingsUpdateSettingEndpointResponse = (Setting);

export type SettingsRegenerateSettingImageData = {
    settingId: string;
    style?: string;
};

export type SettingsRegenerateSettingImageResponse = (ImageGenerationResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsUploadImageData = {
    formData: Body_utils_upload_image;
};

export type UtilsUploadImageResponse = ({
    [key: string]: (string);
});