// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_access_token_api_v1_login_access_token_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Character = {
    id?: string;
    storyboard_id: string;
    name?: (string | null);
    gender?: (string | null);
    age?: (number | null);
    body_build?: (string | null);
    face?: (string | null);
    hair?: (string | null);
    clothes?: (string | null);
    nationality?: (string | null);
    source?: (string | null);
    reference_image_url?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Scene = {
    id?: string;
    storyboard_id: string;
    setting_id: (string | null);
    title?: (string | null);
    sequence_number?: number;
    visual_prompt?: (string | null);
    scene_type?: (string | null);
    reference_image_url?: (string | null);
    reference_video_url?: (string | null);
};

export type Setting = {
    id?: string;
    storyboard_id: string;
    scene_start?: (number | null);
    scene_end?: (number | null);
    name?: (string | null);
    description?: (string | null);
    time_of_day?: (string | null);
    weather?: (string | null);
    art_style?: (string | null);
    reference_image_url?: (string | null);
};

export type StoryBoard = {
    id?: string;
    project_id: string;
    content?: (string | null);
    scenes_json?: (string | null);
    style?: (string | null);
};

/**
 * Request model for creating a storyboard.
 */
export type StoryBoardCreate = {
    project_id: string;
    content: string;
    style?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type CreateStoryboardApiV1StoryboardsPostData = {
    requestBody: StoryBoardCreate;
};

export type CreateStoryboardApiV1StoryboardsPostResponse = (StoryBoard);

export type GetStoryboardApiV1StoryboardsStoryboardIdGetData = {
    storyboardId: string;
};

export type GetStoryboardApiV1StoryboardsStoryboardIdGetResponse = (StoryBoard);

export type GetStoryboardCharactersApiV1StoryboardsStoryboardIdCharactersGetData = {
    storyboardId: string;
};

export type GetStoryboardCharactersApiV1StoryboardsStoryboardIdCharactersGetResponse = (Array<Character>);

export type GetStoryboardSettingsApiV1StoryboardsStoryboardIdSettingsGetData = {
    storyboardId: string;
};

export type GetStoryboardSettingsApiV1StoryboardsStoryboardIdSettingsGetResponse = (Array<Setting>);

export type GetStoryboardScenesApiV1StoryboardsStoryboardIdScenesGetData = {
    storyboardId: string;
};

export type GetStoryboardScenesApiV1StoryboardsStoryboardIdScenesGetResponse = (Array<Scene>);

export type AnalyzeStoryApiV1StoryboardsStoryboardIdAnalyzePostData = {
    generateImages?: boolean;
    storyboardId: string;
    style?: string;
};

export type AnalyzeStoryApiV1StoryboardsStoryboardIdAnalyzePostResponse = ({
    [key: string]: unknown;
});

export type ReadItemsApiV1ItemsGetData = {
    limit?: number;
    skip?: number;
};

export type ReadItemsApiV1ItemsGetResponse = (ItemsPublic);

export type CreateItemApiV1ItemsPostData = {
    requestBody: ItemCreate;
};

export type CreateItemApiV1ItemsPostResponse = (ItemPublic);

export type ReadItemApiV1ItemsIdGetData = {
    id: string;
};

export type ReadItemApiV1ItemsIdGetResponse = (ItemPublic);

export type UpdateItemApiV1ItemsIdPutData = {
    id: string;
    requestBody: ItemUpdate;
};

export type UpdateItemApiV1ItemsIdPutResponse = (ItemPublic);

export type DeleteItemApiV1ItemsIdDeleteData = {
    id: string;
};

export type DeleteItemApiV1ItemsIdDeleteResponse = (Message);

export type LoginAccessTokenApiV1LoginAccessTokenPostData = {
    formData: Body_login_access_token_api_v1_login_access_token_post;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostResponse = (Token);

export type TestTokenApiV1LoginTestTokenPostResponse = (UserPublic);

export type RecoverPasswordApiV1PasswordRecoveryEmailPostData = {
    email: string;
};

export type RecoverPasswordApiV1PasswordRecoveryEmailPostResponse = (Message);

export type ResetPasswordApiV1ResetPasswordPostData = {
    requestBody: NewPassword;
};

export type ResetPasswordApiV1ResetPasswordPostResponse = (Message);

export type RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostData = {
    email: string;
};

export type RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostResponse = (string);

export type CreateUserApiV1PrivateUsersPostData = {
    requestBody: PrivateUserCreate;
};

export type CreateUserApiV1PrivateUsersPostResponse = (UserPublic);

export type ReadUsersApiV1UsersGetData = {
    limit?: number;
    skip?: number;
};

export type ReadUsersApiV1UsersGetResponse = (UsersPublic);

export type CreateUserApiV1UsersPostData = {
    requestBody: UserCreate;
};

export type CreateUserApiV1UsersPostResponse = (UserPublic);

export type ReadUserMeApiV1UsersMeGetResponse = (UserPublic);

export type DeleteUserMeApiV1UsersMeDeleteResponse = (Message);

export type UpdateUserMeApiV1UsersMePatchData = {
    requestBody: UserUpdateMe;
};

export type UpdateUserMeApiV1UsersMePatchResponse = (UserPublic);

export type UpdatePasswordMeApiV1UsersMePasswordPatchData = {
    requestBody: UpdatePassword;
};

export type UpdatePasswordMeApiV1UsersMePasswordPatchResponse = (Message);

export type RegisterUserApiV1UsersSignupPostData = {
    requestBody: UserRegister;
};

export type RegisterUserApiV1UsersSignupPostResponse = (UserPublic);

export type ReadUserByIdApiV1UsersUserIdGetData = {
    userId: string;
};

export type ReadUserByIdApiV1UsersUserIdGetResponse = (UserPublic);

export type UpdateUserApiV1UsersUserIdPatchData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UpdateUserApiV1UsersUserIdPatchResponse = (UserPublic);

export type DeleteUserApiV1UsersUserIdDeleteData = {
    userId: string;
};

export type DeleteUserApiV1UsersUserIdDeleteResponse = (Message);

export type TestEmailApiV1UtilsTestEmailPostData = {
    emailTo: string;
};

export type TestEmailApiV1UtilsTestEmailPostResponse = (Message);

export type HealthCheckApiV1UtilsHealthCheckGetResponse = (boolean);