"""Add Phase 1 Storyboard models

Revision ID: 20250605_phase1
Revises: 1a31ce608336
Create Date: 2025-06-05

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
import uuid

# revision identifiers, used by Alembic.
revision = '20250605_phase1'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create project table
    op.create_table(
        "project",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create mediadata table
    op.create_table(
        "mediadata",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create storyboard table
    op.create_table(
        "storyboard",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False, unique=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scenes_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("style", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create character table
    op.create_table(
        "character",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("storyboard_id", sa.UUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("body_build", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("face", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("hair", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("clothes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nationality", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reference_image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["storyboard_id"], ["storyboard.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create setting table
    op.create_table(
        "setting",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("storyboard_id", sa.UUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("time_of_day", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("weather", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("art_style", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("dominant_colors", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reference_image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["storyboard_id"], ["storyboard.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create scene table
    op.create_table(
        "scene",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("storyboard_id", sa.UUID(), nullable=False),
        sa.Column("setting_id", sa.UUID(), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("narrative_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("visual_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("visual_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scene_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mood", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("camera_angle", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("lighting", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reference_image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reference_video_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["storyboard_id"], ["storyboard.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["setting_id"], ["setting.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create scenecharacterlink table (many-to-many)
    op.create_table(
        "scenecharacterlink",
        sa.Column("scene_id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["scene_id"], ["scene.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["character_id"], ["character.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("scene_id", "character_id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scenecharacterlink")
    op.drop_table("scene")
    op.drop_table("setting")
    op.drop_table("character")
    op.drop_table("storyboard")
    op.drop_table("mediadata")
    op.drop_table("project")
    # ### end Alembic commands ###
