"""update scene model

Revision ID: 5fde2b6b03ce
Revises: f7c3f6cc163e
Create Date: 2026-06-05 20:23:49.438625

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5fde2b6b03ce'
down_revision = 'f7c3f6cc163e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene', sa.Column('narrative_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('scene', sa.Column('visual_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('scene', 'scene_type')
    op.drop_column('scene', 'visual_prompt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene', sa.Column('visual_prompt', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scene', sa.Column('scene_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('scene', 'visual_description')
    op.drop_column('scene', 'narrative_description')
    # ### end Alembic commands ###
