"""update_scene_and_setting_models

Revision ID: f7c3f6cc163e
Revises: 387d5cf98030
Create Date: 2026-06-05 19:53:08.585247

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f7c3f6cc163e'
down_revision = '387d5cf98030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene', 'narrative_description')
    op.drop_column('scene', 'lighting')
    op.drop_column('scene', 'camera_angle')
    op.drop_column('scene', 'visual_description')
    op.drop_column('scene', 'mood')
    op.add_column('setting', sa.Column('scene_start', sa.Integer(), nullable=True))
    op.add_column('setting', sa.Column('scene_end', sa.Integer(), nullable=True))
    op.drop_column('setting', 'dominant_colors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('dominant_colors', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('setting', 'scene_end')
    op.drop_column('setting', 'scene_start')
    op.add_column('scene', sa.Column('mood', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scene', sa.Column('visual_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scene', sa.Column('camera_angle', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scene', sa.Column('lighting', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scene', sa.Column('narrative_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
